# Generated by Django 4.2.6 on 2023-10-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_alter_project_options_project_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Direccion web"),
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="project", verbose_name="Imagen"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripcion"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen del Proyecto",
                "verbose_name_plural": "Imagenes del Proyecto",
            },
        ),
    ]
